function c = latex_ok_commands()
%LATEX_OK_COMMANDS  Live Editor 가 알아듣는 LaTeX 명령 목록
%
%   c = latex_ok_commands()
%
%   왜 이 목록이 필요한가
%     MATLAB Live Editor 는 LaTeX 를 통째로 지원하지 않습니다.
%     모르는 명령을 만나면 **오류를 내지 않고 글자 그대로 남겨 둡니다.**
%     그래서 `\dfrac{1}{s}` 라고 쓰면 화면에 "dfrac1s" 같은 것이 보입니다.
%     오류가 아니라 조용히 깨지므로 목록을 만들어 두고 검사합니다.
%
%   쓰는 곳
%     mlx_from_script  — .mlx 를 만들 때
%     check_mlx        — 다 만든 .mlx 를 다시 검사할 때
%
%   목록에 없어서 자주 깨지는 것
%     \dfrac \tfrac  ->  \frac 을 쓸 것
%     \dots          ->  \ldots
%     \iff \underbrace \longrightarrow  ->  말로 풀거나 \rightarrow
%
%   새 명령을 쓰고 싶으면 Live Editor 에서 직접 확인한 뒤 여기에 추가하십시오.
%
%   제어시스템설계 | 충남대학교 자율운항시스템공학과

c = { ...
  'frac','sqrt','sum','prod','int','lim','left','right','begin','end','array', ...
  'cdot','times','div','pm','mp','approx','neq','ne','leq','geq','le','ge', ...
  'equiv','propto','sim','simeq','cong','ll','gg','ldots', ...
  'ldots','cdots','vdots','ddots','quad','qquad',',',';','!',' ', ...
  'mathbf','mathrm','mathcal','mathbb','textrm','text','rm','bf','it', ...
  'alpha','beta','gamma','delta','epsilon','varepsilon','zeta','eta','theta', ...
  'vartheta','iota','kappa','lambda','mu','nu','xi','pi','rho','sigma','tau', ...
  'upsilon','phi','varphi','chi','psi','omega', ...
  'Gamma','Delta','Theta','Lambda','Xi','Pi','Sigma','Upsilon','Phi','Psi','Omega', ...
  'dot','ddot','hat','bar','tilde','vec','overline','underline', ...
  'infty','partial','nabla','forall','exists','in','notin','subset','cup','cap', ...
  'to','rightarrow','leftarrow','Rightarrow','Leftarrow','Longrightarrow', ...
  'Longleftarrow','leftrightarrow','mapsto', ...
  'sin','cos','tan','sec','csc','cot','arcsin','arccos','arctan', ...
  'sinh','cosh','tanh','log','ln','exp','max','min','deg','circ', ...
  'angle','perp','parallel','prime','ast','star','bullet', ...
  '%','&','#','_','{','}','$','\' };
end
